# Generated by Django 4.1.7 on 2023-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('birthday', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('role_sys', models.CharField(choices=[('Admin', 'Admin'), ('Company', 'Company'), ('Worker', 'Worker')], default='Company', max_length=20, null=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
                ('token_verify', models.CharField(max_length=255, null=True, unique=True)),
                ('token_verify_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('token_reset', models.CharField(max_length=255, null=True, unique=True)),
                ('token_reset_created_at', models.DateTimeField(null=True)),
                ('token_complite_signup', models.CharField(max_length=255, null=True, unique=True)),
                ('token_complite_signup_created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
