# Generated by Django 4.1.7 on 2023-05-14 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Month plan', 'Month plan'), ('In work', 'In work'), ('In test', 'In test'), ('Done', 'Done')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_complite_signup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_complite_signup_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_reset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_reset_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='token_verify_created_at',
        ),
        migrations.CreateModel(
            name='TokensVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_verify', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('token_verify_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TokensReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_reset', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('token_reset_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='TokensCompliteSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_complite_signup', models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('token_complite_signup_created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.user')),
            ],
        ),
    ]
