# Generated by Django 4.1.7 on 2023-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_task_remove_user_token_complite_signup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
