# Generated by Django 4.1.7 on 2023-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_task_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workers',
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(to='mainapp.user'),
        ),
    ]
