# Generated by Django 4.1.7 on 2023-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_task_workers_task_workers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='workers',
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
